### ISSUE TITLE
Select<T> does not works when expression includes contains IN collection

### ISSUE THREAD

**Issue by hmshafeeq** [henkmollema/Dommel#127]
@henkmollema The following combination does not works, i am expecting to work as IN operator.

```C#
List<Category> categories = (conn.Select<Category>(x => x.DeletedAt == null)).ToList(); 
List<Item> tables = (conn.Select<Item>(x => x.DeletedAt == null && categories.Select(s => s.Id).Contains(x.CategoryId))).ToList();
```

Exception : 

```C#
System.InvalidCastException: Unable to cast object of type 'System.Linq.Expressions.MethodCallExpressionN' to type 'System.Linq.Expressions.MemberExpression'.
   at Dommel.DommelMapper.SqlExpression`1.VisitInExpression(MethodCallExpression expression)
   at Dommel.DommelMapper.SqlExpression`1.VisitCallExpression(MethodCallExpression expression)
   at Dommel.DommelMapper.SqlExpression`1.VisitExpression(Expression expression)
   at Dommel.DommelMapper.SqlExpression`1.VisitBinary(BinaryExpression expression)
   at Dommel.DommelMapper.SqlExpression`1.VisitExpression(Expression expression)
   at Dommel.DommelMapper.SqlExpression`1.VisitLambda(LambdaExpression epxression)
   at Dommel.DommelMapper.SqlExpression`1.VisitExpression(Expression expression)
   at Dommel.DommelMapper.SqlExpression`1.AppendToWhere(String conditionOperator, Expression expression)
   at Dommel.DommelMapper.SqlExpression`1.Where(Expression`1 expression)
   at Dommel.DommelMapper.BuildSelectSql[TEntity](IDbConnection connection, Expression`1 predicate, DynamicParameters& parameters)
   at Dommel.DommelMapper.Select[TEntity](IDbConnection connection, Expression`1 predicate, IDbTransaction transaction, Boolean buffered)

```

Am i doing it right way ?

**Comment by henkmollema** [comment]
Can you try this:

```cs
List<Category> categories = (conn.Select<Category>(x => x.DeletedAt == null)).ToList(); 
var categoryIds = categories.Select(s => s.Id).ToArray();
List<Item> tables = (conn.Select<Item>(x => x.DeletedAt == null && categoryIds .Contains(x.CategoryId))).ToList();
```

**Comment by hmshafeeq** [comment]
@henkmollema  Yes, this works. Thanks.
