### ISSUE TITLE
Invalid table name

### ISSUE THREAD

**Issue by premboyapati** [henkmollema/Dommel#227]
Hi there,

I am trying to get a simple select query from oracle database as shown in the below screenshot. It is not working for me, throwing an error, invalid table name. I am 100% sure there is no issue with my table and schema name and column mappings. It seems Dapper/Dommel is causing some issue in generating the sql with correct table name. 

May I know how can I see what SQL query my get statement generating...by enabling logging or some way...

My DBA's will not allow SQL Profilers to see the query...

Error and Code:
![image](https://user-images.githubusercontent.com/2793245/84927290-9cc79880-b09a-11ea-8c64-693cd20a7a26.png)

In case if you are looking for stack trace: 
   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteReader(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, OracleDataReaderImpl& rdrImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[] scnForExecution, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, Int64& internalInitialLOBFS, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, IEnumerable`1 adrianParsedStmt, Boolean isDescribeOnly, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   **_at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior)
   at Dapper.SqlMapper.QueryRowImpl[T](IDbConnection cnn, Row row, CommandDefinition& command, Type effectiveType)
   at Dapper.SqlMapper.QueryFirstOrDefault[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType)
   at Dommel.DommelMapper.Get[TEntity](IDbConnection connection, Object id, IDbTransaction transaction)_**

I would really appreciate your quick response...

Thank you,
Prem.

**Comment by premboyapati** [comment]
I deep dive into the code and found the root cause. Dommel is assuming for some reason, my connection is to SQL server and generating the query to work with SQL server as in below: 
**_select * from [SchemaNAME].[TableNAME] where [Id] = @Id_**

This is method generating sql incorrectly as if I am trying to work with SQL server....
![image](https://user-images.githubusercontent.com/2793245/84941699-bc1cf080-b0af-11ea-9aff-a59b63ea3f47.png)

**Comment by igordibuccio** [comment]
My connection is with SqlServer and I still have the same error

**Comment by igordibuccio** [comment]
The error that it generates in a project using SqlServer is this ..

Message: Não foi possível carregar o tipo IColumnNameResolver do assembly Dommel, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null.

StackTrace: Dapper.FluentMap.Dommel.FluentMapConfigurationExtensions.ForDommel(FluentMapConfiguration config)
   em xFidelidade.Data.RegisterMappings.<>c.<Register>b__0_0(FluentMapConfiguration config) em D:\Dados\Projetos\xFidelidade\src\xFidelidade.Data\RegisterMappings.cs:linha 19
   em Dapper.FluentMap.FluentMapper.Initialize(Action`1 configure)
   em xFidelidade.Data.RegisterMappings.Register() em D:\Dados\Projetos\xFidelidade\src\xFidelidade.Data\RegisterMappings.cs:linha 13
   em xFidelidade.Data.Repository.Repository`1..ctor(IDbConnection connection) em D:\Dados\Projetos\xFidelidade\src\xFidelidade.Data\Repository\Repository.cs:linha 18
   em xFidelidade.Data.Repository.CategoriaClienteRepository..ctor(IDbConnection connection) em D:\Dados\Projetos\xFidelidade\src\xFidelidade.Data\Repository\CategoriaClienteRepository.cs:linha 13
   em xFidelidade.CategoriaCliente.frmCategoriaCliente.frmCategoriaCliente_Load(Object sender, EventArgs e) em D:\Dados\Projetos\xFidelidade\src\xFidelidade\CategoriaCliente\frmCategoriaCliente.cs:linha 26
   em System.Windows.Forms.Form.OnLoad(EventArgs e)
   em System.Windows.Forms.Form.OnCreateControl()
   em System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   em System.Windows.Forms.Control.CreateControl()
   em System.Windows.Forms.Control.WmShowWindow(Message& m)
   em System.Windows.Forms.Control.WndProc(Message& m)
   em System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   em System.Windows.Forms.Form.WmShowWindow(Message& m)
   em System.Windows.Forms.Form.WndProc(Message& m)
   em System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   em System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   em System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by premboyapati** [comment]
> My connection is with SqlServer and I still have the same error

Did you check your model with correct attributes...your model class should be like this....

[Table("MY_TABLE_NAME", Schema = "MY_SCHEMA_NAME")]
    public class MyModel
    {
        [Key]
        [Column("Id")]
        public long Id { get; set; }

        [Column("name")]
        public string Name { get; set; }

        [Column("updatedBy")]
        public string LastModifiedBy { get; set; }
    }

**Comment by igordibuccio** [comment]
My map is like this, I use FluentMap
![Mapping](https://user-images.githubusercontent.com/8548433/84943016-1de25800-b0ba-11ea-9eba-7be3f6874c16.png)

**Comment by premboyapati** [comment]
> IColumnNameResolver

I think I am right...It is looking for Column Attribute

**Comment by premboyapati** [comment]
> My map is like this, I use FluentMap
> ![Mapping](https://user-images.githubusercontent.com/8548433/84943016-1de25800-b0ba-11ea-9eba-7be3f6874c16.png)

I tried like you intitially but not working...comment this code and decorate your model using _**Table and Column**_ attributes...That's why you are getting **_'IColumnNameResolver_** 

![image](https://user-images.githubusercontent.com/2793245/84943197-030be580-b0b2-11ea-8073-be485ae55413.png)

**Comment by igordibuccio** [comment]
> > Meu mapa é assim, eu uso o FluentMap
> > ![Mapeamento](https://user-images.githubusercontent.com/8548433/84943016-1de25800-b0ba-11ea-9eba-7be3f6874c16.png)
> 
> Tentei como você inicialmente, mas não está funcionando ... comente seu código de mapeamento e decore seu modelo usando os atributos _**Tabela e Coluna**_ ... É por isso que você está recebendo **_'IColumnNameResolver_**
> 
> ![imagem](https://user-images.githubusercontent.com/2793245/84943197-030be580-b0b2-11ea-8073-be485ae55413.png)

When I change the model by inserting the annotations in it, it works correctly.
I'm sorry, I'm still learning to use this type of technology, but is this a mistake and will it be corrected? or will it continue like this?
I like to use FluentMap, because I don't make my models "dirty"

**Comment by premboyapati** [comment]
> > > Meu mapa é assim, eu uso o FluentMap
> > > ![Mapeamento](https://user-images.githubusercontent.com/8548433/84943016-1de25800-b0ba-11ea-9eba-7be3f6874c16.png)
> > 
> > 
> > Tentei como você inicialmente, mas não está funcionando ... comente seu código de mapeamento e decore seu modelo usando os atributos _**Tabela e Coluna**_ ... É por isso que você está recebendo **_'IColumnNameResolver_**
> > ![imagem](https://user-images.githubusercontent.com/2793245/84943197-030be580-b0b2-11ea-8073-be485ae55413.png)
> 
> When I change the model by inserting the annotations in it, it works correctly.
> I'm sorry, I'm still learning to use this type of technology, but is this a mistake and will it be corrected? or will it continue like this?
> I like to use FluentMap, because I don't make my models "dirty"

I am not author of this code base. I do not know if this is an issue or not. With my experience, I would say there is huge GAP between what documentation says and what codebase works...

**_I will leave your question to answer the codebase owner/stakeholder..._**

I am glad to hear that my suggestion worked for you...whenever you think something worked, please give thumbs up, so that others can quickly look at it and try that same solution.

Good luck again!

**Comment by premboyapati** [comment]
Hi  there,

Do you guys know these basic issues exists in the code...this code is working only with the property based column attribute and with fluent mapping....

Does this codebase works with Oracle database? If yes, Can you point me to the documentation. 
If no, Do I need to implement any interface to work with oracle? How can I do that?

Thanks
Prem.

**Comment by henkmollema** [comment]
Dapper.FluentMap.Json does not work with Dommel v2 yet, but there is a PR in progress: https://github.com/henkmollema/Dapper-FluentMap/pull/105

As for Oracle support, you should implement a custom `ISqlBuilder` for Oracle (e.g. `OracleSqlBuilder` and add it with in your startup code:

```cs
DommelMapper.AddSqlBuilder(typeof(OracleConnection), new OracleSqlBuilder());
```
